# Generated by Django 5.1.7 on 2025-03-18 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["due_data"],
                "verbose_name": "Tarefa",
                "verbose_name_plural": "Tarefas",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Usuario", "verbose_name_plural": "Usuarios"},
        ),
    ]
